# Copyright (C) 2026 Julian Valentin
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

name: Renovate
on:
  push:
  schedule:
    # need to run once for creating the branches, and then again once to automerge each created branch one-by-one after
    # the CI checks have passed
    - cron: 24 */2 * * *
  workflow_dispatch:
permissions:
  contents: read
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Renovate
        uses: renovatebot/github-action@973d3e5a68e735a444e8c03432b66eedb343c302 # v46.2.0
        with:
          configurationFile: self-hosted.json
          renovate-version: 44.5.3@sha256:0de2072bc4c87e1744158adfb8ccd9f49c5bd2da5a0c14bc4b0c90a7cdaab54f # renovate: datasource=docker depName=ghcr.io/renovatebot/renovate
          token: ${{ secrets.VALENTJN_RENOVATE_PAT }}
        env:
          LOG_LEVEL: debug
