# Copyright (C) 2026 Julian Valentin
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

name: Renovate
on:
  push:
  schedule:
    # need to run once for creating the branches, and then again once to automerge each created branch one-by-one after
    # the CI checks have passed
    - cron: 24 */2 * * *
  workflow_dispatch:
permissions:
  contents: read
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Renovate
        uses: renovatebot/github-action@eb932558ad942cccfd8211cf535f17ff183a9f74 # v46.1.9
        with:
          configurationFile: self-hosted.json
          renovate-version: 43.141.5@sha256:8fb9e3cfdadc0994fb87f57be624d1c1940c41c1c53c074465caff85a2b6d3a4 # renovate: datasource=docker depName=ghcr.io/renovatebot/renovate
          token: ${{ secrets.VALENTJN_RENOVATE_PAT }}
        env:
          LOG_LEVEL: debug
